export type WorldBossSeed = {
  id: string;
  entryId: number;
  name: string;
  zone: string;
  continent: string;
  level: string;
  difficulty: "elite" | "rare-elite" | "mini-boss";
  respawnHours: number;
  mechanic: string;
  bulkLoot: string;
  bulkItemId: number;
  bulkItemCount: number;
  rareLoot: string;
  rareItemId: number;
  rareDropChance: string;
  spawnCoords: string;
  enabled: boolean;
  notes: string;
};

export const WORLD_BOSSES_60: WorldBossSeed[] = [
  // ================= Eastern Kingdoms (1-12) =================
  {
    id: "grimjaw-forestlord",
    entryId: 900001,
    name: "Гримджо Лесной Владыка",
    zone: "Элвиннский лес",
    continent: "Восточные королевства",
    level: "30-35",
    difficulty: "mini-boss",
    respawnHours: 3,
    mechanic: "Призывает стаю свирепых волков, укоренение лозами по площади 20м",
    bulkLoot: "Плотная кожа x1000",
    bulkItemId: 2318,
    bulkItemCount: 1000,
    rareLoot: "Клык Лесного Владыки (трансмог-посох, аура зеленых листьев)",
    rareItemId: 950001,
    rareDropChance: "2%",
    spawnCoords: "X: -9450, Y: -920, Z: 58",
    enabled: true,
    notes: "Кожевничество. Спавн у Волчьего логова к югу от Златоземья.",
  },
  {
    id: "widow-matriarch",
    entryId: 900002,
    name: "Матриарх Ирша Тенепрядка",
    zone: "Сумеречный лес",
    continent: "Восточные королевства",
    level: "32-36",
    difficulty: "mini-boss",
    respawnHours: 3,
    mechanic: "Кислотный ядовитый плевок по конусу, паутинный кокон на танка",
    bulkLoot: "Шёлковая ткань x1000",
    bulkItemId: 2589,
    bulkItemCount: 1000,
    rareLoot: "Выкройка: Плащ из паучьего шёлка (уникальный сет трансмогрификации)",
    rareItemId: 950002,
    rareDropChance: "1.5%",
    spawnCoords: "X: -10520, Y: -1210, Z: 42",
    enabled: true,
    notes: "Портняжество. Обитает в склепе у поместья Стонсов.",
  },
  {
    id: "ironhide-colossus",
    entryId: 900003,
    name: "Железнокожий Колосс",
    zone: "Красногорье",
    continent: "Восточные королевства",
    level: "38-42",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Землетрясение с оглушением на 3 сек, каменная кожа (-50% урона)",
    bulkLoot: "Железная руда x1000",
    bulkItemId: 2842,
    bulkItemCount: 1000,
    rareLoot: "Ядро Колосса (реагент для улучшения экипировки до 1000 ilvl)",
    rareItemId: 950003,
    rareDropChance: "3%",
    spawnCoords: "X: -9280, Y: -2180, Z: 130",
    enabled: true,
    notes: "Горное дело. Появляется у каньона Каменного Когтя.",
  },
  {
    id: "rotting-harvestman",
    entryId: 900004,
    name: "Гниющий Жнец Тыквовин",
    zone: "Западный край",
    continent: "Восточные королевства",
    level: "25-30",
    difficulty: "mini-boss",
    respawnHours: 3,
    mechanic: "Ядовитое облако гнили, призыв тыквоголовых пугал-камикадзе",
    bulkLoot: "Льняная ткань x1000",
    bulkItemId: 2589,
    bulkItemCount: 1000,
    rareLoot: "Поводья 'Тыквенного Ужаса' (уникальный маунт-скакун вне сезона)",
    rareItemId: 950004,
    rareDropChance: "1%",
    spawnCoords: "X: -10640, Y: 1120, Z: 35",
    enabled: true,
    notes: "Портняжество. Ночной спавн на заброшенных фермах Западного края.",
  },
  {
    id: "bloodscale-devourer",
    entryId: 900005,
    name: "Кровочешуйчатый Пожиратель",
    zone: "Северная Тернистая долина",
    continent: "Восточные королевства",
    level: "45-50",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Смертоносное кровотечение, погружение в реку и внезапный выпад",
    bulkLoot: "Грубая кожа x1000",
    bulkItemId: 2934,
    bulkItemCount: 1000,
    rareLoot: "Чешуя Пожирателя (токен полного сета чешуйчатой брони)",
    rareItemId: 950005,
    rareDropChance: "2%",
    spawnCoords: "X: -11820, Y: -210, Z: 18",
    enabled: true,
    notes: "Кожевничество. Плавает в реке у водопада Назифер.",
  },
  {
    id: "obsidian-behemoth",
    entryId: 900006,
    name: "Обсидиановый Бегемот",
    zone: "Бесплодные земли",
    continent: "Восточные королевства",
    level: "48-52",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Дыхание раскаленной лавы, обсидиановый щит (отражение 2 заклинаний)",
    bulkLoot: "Мифриловая руда x1000",
    bulkItemId: 3858,
    bulkItemCount: 1000,
    rareLoot: "Обсидиановый дракончик (редкий боевой питомец)",
    rareItemId: 950006,
    rareDropChance: "1%",
    spawnCoords: "X: -6840, Y: -3210, Z: 245",
    enabled: true,
    notes: "Горное дело. Утес Драконьих Раскопок.",
  },
  {
    id: "duskwood-shadowweaver",
    entryId: 900027,
    name: "Тенепряд Морт'агар",
    zone: "Перевал Мертвого Ветра",
    continent: "Восточные королевства",
    level: "70-72",
    difficulty: "elite",
    respawnHours: 5,
    mechanic: "Каражанское искажение времени, цепи теней, стяжка игроков",
    bulkLoot: "Чародейный прах x1000",
    bulkItemId: 22445,
    bulkItemCount: 1000,
    rareLoot: "Теневой фолиант Каражана (обучающий свиток забытого заклинания)",
    rareItemId: 950027,
    rareDropChance: "1.5%",
    spawnCoords: "X: -11120, Y: -1980, Z: 75",
    enabled: true,
    notes: "Наложение чар. Патрулирует дорогу у подножия башни Каражан.",
  },
  {
    id: "arathi-stormherald",
    entryId: 900028,
    name: "Громовестник Стромгарда",
    zone: "Нагорье Арати",
    continent: "Восточные королевства",
    level: "40-44",
    difficulty: "rare-elite",
    respawnHours: 3,
    mechanic: "Цепная молния по 5 целям, щит бури, отталкивание ветром",
    bulkLoot: "Тяжелый камень x1000",
    bulkItemId: 3577,
    bulkItemCount: 1000,
    rareLoot: "Накидка Громового Шторма (уникальная гербовая накидка со спецэффектом)",
    rareItemId: 950028,
    rareDropChance: "2%",
    spawnCoords: "X: -1320, Y: -2540, Z: 62",
    enabled: true,
    notes: "Горное дело. В руинах крепости Стромгард.",
  },
  {
    id: "hinterlands-primalist",
    entryId: 900029,
    name: "Первобытная Змея Джинта'Алор",
    zone: "Внутренние земли",
    continent: "Восточные королевства",
    level: "50-54",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Токсичный туман, ядовитый укус со снижением брони на 40%",
    bulkLoot: "Призрачная поганка x1000",
    bulkItemId: 8838,
    bulkItemCount: 1000,
    rareLoot: "Клык Джинта'Алор (кинжал с визуальным зеленым дымом)",
    rareItemId: 950029,
    rareDropChance: "1.5%",
    spawnCoords: "X: 280, Y: -3980, Z: 145",
    enabled: true,
    notes: "Травничество. Вершина священного алтаря троллей.",
  },
  {
    id: "plaguelands-bonegolem",
    entryId: 900030,
    name: "Костяной Мучитель Араж",
    zone: "Западные Чумные земли",
    continent: "Восточные королевства",
    level: "58-60",
    difficulty: "elite",
    respawnHours: 5,
    mechanic: "Вихрь костяных осколков, страх смерти, призыв скелетов-магов",
    bulkLoot: "Руническая ткань x1000",
    bulkItemId: 14047,
    bulkItemCount: 1000,
    rareLoot: "Череп Мучителя (игрушка: превращает союзников в скелетов)",
    rareItemId: 950030,
    rareDropChance: "1%",
    spawnCoords: "X: 1820, Y: -1450, Z: 82",
    enabled: true,
    notes: "Портняжество. Центр Андорала у разрушенной ратуши.",
  },
  {
    id: "stranglethorn-hydra",
    entryId: 900031,
    name: "Многоглавая Гидра Гурбаши",
    zone: "Мыс Тернистый",
    continent: "Восточные королевства",
    level: "42-46",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Тройное дыхание (лед, огонь, яд), регенерация голов при 30% HP",
    bulkLoot: "Толстая кожа x1000",
    bulkItemId: 4304,
    bulkItemCount: 1000,
    rareLoot: "Детеныш Гурбаши-Гидры (эксклюзивный водный питомец)",
    rareItemId: 950031,
    rareDropChance: "1%",
    spawnCoords: "X: -12450, Y: -480, Z: 8",
    enabled: true,
    notes: "Кожевничество. Бухта у пиратского лагеря.",
  },
  {
    id: "lochmodan-trogg-king",
    entryId: 900032,
    name: "Король Троггов Камнебрюх",
    zone: "Лок Модан",
    continent: "Восточные королевства",
    level: "22-26",
    difficulty: "mini-boss",
    respawnHours: 3,
    mechanic: "Оглушающий вопль, швыряние булыжников в дальних бойцов",
    bulkLoot: "Медная руда x1000",
    bulkItemId: 2770,
    bulkItemCount: 1000,
    rareLoot: "Каменная дубина Камнебрюха (двуручная булава для трансмога)",
    rareItemId: 950032,
    rareDropChance: "2.5%",
    spawnCoords: "X: -5420, Y: -3120, Z: 310",
    enabled: true,
    notes: "Горное дело. Шахта Камнебрюхов.",
  },

  // ================= Kalimdor (13-24) =================
  {
    id: "devilsaur-king",
    entryId: 900007,
    name: "Король Дьяволозавров Праоснова",
    zone: "Кратер Ун'Горо",
    continent: "Калимдор",
    level: "54-58",
    difficulty: "elite",
    respawnHours: 5,
    mechanic: "Землетрясущий топот (страх 4 сек), рывок с пробитием брони",
    bulkLoot: "Прочная кожа x1000",
    bulkItemId: 4234,
    bulkItemCount: 1000,
    rareLoot: "Окаменелое яйцо Праосновы (маунт-детеныш дьяволозавра)",
    rareItemId: 950007,
    rareDropChance: "1%",
    spawnCoords: "X: -6980, Y: -1250, Z: -260",
    enabled: true,
    notes: "Кожевничество. Респавн у вулканического жерла Ун'Горо.",
  },
  {
    id: "frostmane-ancient",
    entryId: 900008,
    name: "Древний Морозной Гривы",
    zone: "Зимние ключи",
    continent: "Калимдор",
    level: "58-60",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Ледяная метель, кольцо холода, ледяные шипы из-под земли",
    bulkLoot: "Руническая ткань x1000",
    bulkItemId: 14047,
    bulkItemCount: 1000,
    rareLoot: "Замёрзшее сердце Древнего (реагент 'Концентрата силы')",
    rareItemId: 950008,
    rareDropChance: "2.5%",
    spawnCoords: "X: 6820, Y: -4150, Z: 720",
    enabled: true,
    notes: "Портняжество. Озеро Кель'Терил.",
  },
  {
    id: "ancient-treant-warden",
    entryId: 900009,
    name: "Страж-древень Хранитель Рощи",
    zone: "Фералас",
    continent: "Калимдор",
    level: "44-48",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Удушающие корни, периодическое исцеление листвой на 10%",
    bulkLoot: "Дикий шалфей x1000",
    bulkItemId: 3820,
    bulkItemCount: 1000,
    rareLoot: "Сердце леса (реликвия друида: открывает форму древня)",
    rareItemId: 950009,
    rareDropChance: "1.5%",
    spawnCoords: "X: -4320, Y: 1820, Z: 55",
    enabled: true,
    notes: "Травничество. Роща Ужаса возле Забытого Города.",
  },
  {
    id: "qiraji-broodmother",
    entryId: 900026,
    name: "Кираджийская Матка Роя",
    zone: "Силитус",
    continent: "Калимдор",
    level: "60-62",
    difficulty: "elite",
    respawnHours: 6,
    mechanic: "Песчаный вихрь, кислотные лужи, призыв роя мелких кираджей",
    bulkLoot: "Ториевая руда x1000",
    bulkItemId: 12365,
    bulkItemCount: 1000,
    rareLoot: "Хитиновый панцирь Матки (реагент улучшения 985→1000 ilvl)",
    rareItemId: 950026,
    rareDropChance: "2%",
    spawnCoords: "X: -7120, Y: 1050, Z: 12",
    enabled: true,
    notes: "Горное дело. У самых Врат Ан'Киража.",
  },
  {
    id: "barrens-thunderlizard",
    entryId: 900033,
    name: "Громозев Владыка Степей",
    zone: "Северные Степи",
    continent: "Калимдор",
    level: "24-28",
    difficulty: "mini-boss",
    respawnHours: 3,
    mechanic: "Удар грозы по всей группе, электрическое силовое поле",
    bulkLoot: "Жесткая кожа x1000",
    bulkItemId: 2319,
    bulkItemCount: 1000,
    rareLoot: "Громовой рог (игрушка: вызывает бурю над игроком)",
    rareItemId: 950033,
    rareDropChance: "2%",
    spawnCoords: "X: 320, Y: -2410, Z: 92",
    enabled: true,
    notes: "Кожевничество. Оазис Забытой Воды.",
  },
  {
    id: "tanaris-sandreaver",
    entryId: 900034,
    name: "Песчаный Разоритель Скорпокс",
    zone: "Танарис",
    continent: "Калимдор",
    level: "48-52",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Зарывание в песок, ядовитый хвост с параличом на 2 сек",
    bulkLoot: "Мифриловая руда x1000",
    bulkItemId: 3858,
    bulkItemCount: 1000,
    rareLoot: "Жало Скорпокса (одноручный меч в виде жала скорпиона)",
    rareItemId: 950034,
    rareDropChance: "1.5%",
    spawnCoords: "X: -8850, Y: -3420, Z: 18",
    enabled: true,
    notes: "Горное дело. Пески Взморья Конец Времени.",
  },
  {
    id: "darkshore-spectral-whale",
    entryId: 900035,
    name: "Призрачный Левиафан Темных Берегов",
    zone: "Темные берега",
    continent: "Калимдор",
    level: "20-25",
    difficulty: "mini-boss",
    respawnHours: 3,
    mechanic: "Водяной смерч, волна прилива с отбрасыванием на берег",
    bulkLoot: "Ракушечник и жемчуг x500",
    bulkItemId: 5500,
    bulkItemCount: 500,
    rareLoot: "Жемчужина Глубин (редкий подводный маунт-скат)",
    rareItemId: 950035,
    rareDropChance: "1%",
    spawnCoords: "X: 6120, Y: 120, Z: -5",
    enabled: true,
    notes: "Рыбная ловля и ювелирное дело. В океане у Аубердина.",
  },
  {
    id: "desolace-kodo-matriarch",
    entryId: 900036,
    name: "Матриарх Кодо Призрачной Равнины",
    zone: "Пустоши",
    continent: "Калимдор",
    level: "35-39",
    difficulty: "mini-boss",
    respawnHours: 3,
    mechanic: "Пыльная буря, таран рогами со сбитием с ног",
    bulkLoot: "Толстая кожа x1000",
    bulkItemId: 4304,
    bulkItemCount: 1000,
    rareLoot: "Поводья белого боевого кодо (редкий трансмог-маунт)",
    rareItemId: 950036,
    rareDropChance: "2%",
    spawnCoords: "X: -1240, Y: 1850, Z: 78",
    enabled: true,
    notes: "Кожевничество. Кладбище Кодо.",
  },
  {
    id: "azshara-arcanegolem",
    entryId: 900037,
    name: "Чародейский Исполин Высокорожденных",
    zone: "Азшара",
    continent: "Калимдор",
    level: "48-52",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Чародейская вспышка, поглощение магии с баффом силы заклинаний",
    bulkLoot: "Слиток тория x1000",
    bulkItemId: 12359,
    bulkItemCount: 1000,
    rareLoot: "Фрагмент Колодца Вечности (реликвия чародея)",
    rareItemId: 950037,
    rareDropChance: "1.5%",
    spawnCoords: "X: 3410, Y: -4120, Z: 110",
    enabled: true,
    notes: "Горное дело. У руин храма Зин-Азшари.",
  },
  {
    id: "stonetalon-harpy-queen",
    entryId: 900038,
    name: "Королева Гарпий Ветрокрылая",
    zone: "Когтистые горы",
    continent: "Калимдор",
    level: "28-32",
    difficulty: "mini-boss",
    respawnHours: 3,
    mechanic: "Пронзительный крик (немота 4 сек), пикирование с воздуха",
    bulkLoot: "Шерсть и перья x1000",
    bulkItemId: 4338,
    bulkItemCount: 1000,
    rareLoot: "Оперение Ветрокрылой (трансмог-наплечники с эффектом перьев)",
    rareItemId: 950038,
    rareDropChance: "2%",
    spawnCoords: "X: 1250, Y: 1120, Z: 340",
    enabled: true,
    notes: "Портняжество. Гнездовье на вершине пика.",
  },
  {
    id: "felwood-corruptor",
    entryId: 900039,
    name: "Осквернитель Древогуб",
    zone: "Оскверненный лес",
    continent: "Калимдор",
    level: "52-56",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Скверна под ногами игроков, вытягивание жизни из союзников",
    bulkLoot: "Слезы Артаса x1000",
    bulkItemId: 8836,
    bulkItemCount: 1000,
    rareLoot: "Очищенное семя Скверны (боевой питомец Оскверненный саженец)",
    rareItemId: 950039,
    rareDropChance: "1%",
    spawnCoords: "X: 4850, Y: -1210, Z: 395",
    enabled: true,
    notes: "Травничество. Центр Ядовитого Источника.",
  },
  {
    id: "dustwallow-blackdragon",
    entryId: 900040,
    name: "Драконид-Опустошитель Саргот",
    zone: "Пылевые топи",
    continent: "Калимдор",
    level: "40-44",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Раскалывающий удар хвостом, огненная лава по земле",
    bulkLoot: "Чешуя черного дракона x1000",
    bulkItemId: 15414,
    bulkItemCount: 1000,
    rareLoot: "Шлем Драконьего Полководца (трансмог латный шлем)",
    rareItemId: 950040,
    rareDropChance: "2%",
    spawnCoords: "X: -3650, Y: -3120, Z: 32",
    enabled: true,
    notes: "Кожевничество. Логово возле Ониксии.",
  },

  // ================= Outland (25-32) =================
  {
    id: "fel-iron-colossus",
    entryId: 900012,
    name: "Колосс Оскверненного Железа",
    zone: "Полуостров Адского Пламени",
    continent: "Запределье",
    level: "63-66",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Огненный смерч Скверны, мощное обрушение с уроном по площади 30м",
    bulkLoot: "Оскверненное железо x1000",
    bulkItemId: 23424,
    bulkItemCount: 1000,
    rareLoot: "Осколок ядра Скверны (реагент для улучшения 'Концентрат силы')",
    rareItemId: 950012,
    rareDropChance: "2%",
    spawnCoords: "X: -240, Y: 2150, Z: 110",
    enabled: true,
    notes: "Горное дело. Руины Разжигателя Скверны.",
  },
  {
    id: "bog-lord-muckmaw",
    entryId: 900013,
    name: "Болотный Владыка Грязепасть",
    zone: "Зангартопь",
    continent: "Запределье",
    level: "64-67",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Замедляющая споровая трясина, проглатывание игрока в брюхо",
    bulkLoot: "Кожа сквернотопыря x1000",
    bulkItemId: 21877,
    bulkItemCount: 1000,
    rareLoot: "Мешочек, покрытый спорами (открывает редкий трансмог-сет)",
    rareItemId: 950013,
    rareDropChance: "1.5%",
    spawnCoords: "X: -180, Y: 5850, Z: 22",
    enabled: true,
    notes: "Кожевничество. Обитает в Споровом лесу Зангартопи.",
  },
  {
    id: "shadow-council-warlock",
    entryId: 900014,
    name: "Верховный чернокнижник Совета Теней",
    zone: "Долина Призрачной Луны",
    continent: "Запределье",
    level: "68-70",
    difficulty: "elite",
    respawnHours: 5,
    mechanic: "Теневые метеоры, проклятие немоты на всех кастеров на 5 сек",
    bulkLoot: "Ткань Скверны x1000",
    bulkItemId: 14256,
    bulkItemCount: 1000,
    rareLoot: "Эссенция Тени (топовый обучающий том чернокнижника)",
    rareItemId: 950014,
    rareDropChance: "1%",
    spawnCoords: "X: -4120, Y: 1120, Z: 75",
    enabled: true,
    notes: "Портняжество + Забытые способности. У подножия Черного Храма.",
  },
  {
    id: "windroc-alpha",
    entryId: 900010,
    name: "Вожак Скальных Грифов",
    zone: "Награнд",
    continent: "Запределье",
    level: "66-68",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Смертоносное пикирование, вихрь перьев с отталкиванием в пропасть",
    bulkLoot: "Кожа копытня x1000",
    bulkItemId: 25700,
    bulkItemCount: 1000,
    rareLoot: "Коготь Вожака (трансмог боевой клинок с уникальным свечением)",
    rareItemId: 950010,
    rareDropChance: "2%",
    spawnCoords: "X: -1450, Y: 8420, Z: 28",
    enabled: true,
    notes: "Кожевничество. Парящие острова над Награндом.",
  },
  {
    id: "terokkar-bone-witch",
    entryId: 900041,
    name: "Костяная Ведьма Аукиндона",
    zone: "Лес Тероккар",
    continent: "Запределье",
    level: "65-68",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Вой падших душ, призыв духов дренеев, вихрь призраков",
    bulkLoot: "Адамантитовая руда x1000",
    bulkItemId: 23425,
    bulkItemCount: 1000,
    rareLoot: "Костяная корона Аукиндона (трансмог шлем с эффектом левитации)",
    rareItemId: 950041,
    rareDropChance: "1.5%",
    spawnCoords: "X: -3320, Y: 4950, Z: -5",
    enabled: true,
    notes: "Горное дело. Костяные пустоши возле Аукиндона.",
  },
  {
    id: "blades-edge-gronn-slayer",
    entryId: 900042,
    name: "Гронн-Палач Кровоглаз",
    zone: "Острогорье",
    continent: "Запределье",
    level: "67-70",
    difficulty: "elite",
    respawnHours: 5,
    mechanic: "Удар дубиной с раскалыванием брони, топот с замедлением на 70%",
    bulkLoot: "Ториевая и кобальтовая руда x1000",
    bulkItemId: 23425,
    bulkItemCount: 1000,
    rareLoot: "Око Гронна (тринкет: призывает мини-гронна в бою)",
    rareItemId: 950042,
    rareDropChance: "1%",
    spawnCoords: "X: 2150, Y: 6120, Z: 180",
    enabled: true,
    notes: "Горное дело. Ущелье Кровавого Молота.",
  },
  {
    id: "netherstorm-mana-wraith",
    entryId: 900043,
    name: "Мана-Призрак Бури Эфира",
    zone: "Пустоверть",
    continent: "Запределье",
    level: "68-71",
    difficulty: "elite",
    respawnHours: 5,
    mechanic: "Мана-сжигание, электро-взрыв по цепи, эфирный щит неуязвимости",
    bulkLoot: "Изначальная мана и эфир x500",
    bulkItemId: 22457,
    bulkItemCount: 500,
    rareLoot: "Эфириумский телепортер (игрушка: мгновенный перенос в Пустоверть)",
    rareItemId: 950043,
    rareDropChance: "2%",
    spawnCoords: "X: 3820, Y: 3210, Z: 145",
    enabled: true,
    notes: "Наложение чар. Кузница Маны Ара.",
  },
  {
    id: "outland-infernal-lord",
    entryId: 900044,
    name: "Повелитель Инферналов Вулканор",
    zone: "Полуостров Адского Пламени",
    continent: "Запределье",
    level: "70-72",
    difficulty: "elite",
    respawnHours: 6,
    mechanic: "Падение метеоритов Скверны, огненная аура 5000 урона/сек вокруг",
    bulkLoot: "Кориевая руда x500",
    bulkItemId: 23427,
    bulkItemCount: 500,
    rareLoot: "Ядро Повелителя Инферналов (маунт Пылающий Инфернал)",
    rareItemId: 950044,
    rareDropChance: "0.8%",
    spawnCoords: "X: -520, Y: 3890, Z: 85",
    enabled: true,
    notes: "Горное дело. Врата Легиона на севере полуострова.",
  },

  // ================= Northrend (33-42) =================
  {
    id: "mammoth-matriarch",
    entryId: 900015,
    name: "Мать-мамонтиха Ледяного Клыка",
    zone: "Борейская тундра",
    continent: "Нордскол",
    level: "70-73",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Топот стада с оглушением, подбрасывание танка бивнями на 15м",
    bulkLoot: "Борейская кожа x1000",
    bulkItemId: 33568,
    bulkItemCount: 1000,
    rareLoot: "Трофей 'Бивень Мамонта' (эксклюзивное украшение гильд-холла)",
    rareItemId: 950015,
    rareDropChance: "2%",
    spawnCoords: "X: 3450, Y: 4120, Z: 65",
    enabled: true,
    notes: "Кожевничество. Равнины Ледяного Клыка.",
  },
  {
    id: "primal-devourer",
    entryId: 900016,
    name: "Первобытный Пожиратель Джунглей",
    zone: "Низина Шолазар",
    continent: "Нордскол",
    level: "76-78",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Регенерация от цветов джунглей, токсичный плевок на 5 игроков",
    bulkLoot: "Морозная ткань x1000",
    bulkItemId: 33470,
    bulkItemCount: 1000,
    rareLoot: "Первородное яйцо динозавра (боевой питомец прото-раптор)",
    rareItemId: 950016,
    rareDropChance: "1%",
    spawnCoords: "X: 5820, Y: 4320, Z: -75",
    enabled: true,
    notes: "Портняжество. Пруд Идолов.",
  },
  {
    id: "saronite-guardian",
    entryId: 900017,
    name: "Хранитель Саронитовых Жил",
    zone: "Ледяная Корона",
    continent: "Нордскол",
    level: "80-82",
    difficulty: "elite",
    respawnHours: 6,
    mechanic: "Саронитовое безумие (шепот Древнего Бога), ледяная броня",
    bulkLoot: "Саронитовая руда x1000",
    bulkItemId: 36909,
    bulkItemCount: 1000,
    rareLoot: "Замороженное ядро Саронита (реагент 'Концентрата силы')",
    rareItemId: 950017,
    rareDropChance: "2%",
    spawnCoords: "X: 6920, Y: 2120, Z: 512",
    enabled: true,
    notes: "Горное дело. Карьер Саронита к северу от Цитадели.",
  },
  {
    id: "vrykul-ancestor",
    entryId: 900018,
    name: "Дух Предка Врайкулов Бьорн",
    zone: "Ревущий фьорд",
    continent: "Нордскол",
    level: "71-74",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Боевой клич древних врайкулов (+100% урона), бросок топора",
    bulkLoot: "Борейская кожа x1000",
    bulkItemId: 33568,
    bulkItemCount: 1000,
    rareLoot: "Руна Предков Врайкулов (токен уникального трансмог-сета викингов)",
    rareItemId: 950018,
    rareDropChance: "1.5%",
    spawnCoords: "X: 1820, Y: -4820, Z: 145",
    enabled: true,
    notes: "Кожевничество. Древний курган близ Утгарда.",
  },
  {
    id: "dragonblight-frostwyrm",
    entryId: 900045,
    name: "Ледяной Змей Хладный Мор",
    zone: "Драконий Погост",
    continent: "Нордскол",
    level: "74-77",
    difficulty: "elite",
    respawnHours: 5,
    mechanic: "Глубокая заморозка всей площадки, призыв ледяных вурдалаков",
    bulkLoot: "Титановая руда x500",
    bulkItemId: 36910,
    bulkItemCount: 500,
    rareLoot: "Костяной хребет Змея (трансмог-двуручный меч с ледяным паром)",
    rareItemId: 950045,
    rareDropChance: "1.5%",
    spawnCoords: "X: 3820, Y: 850, Z: 45",
    enabled: true,
    notes: "Горное дело. Погост Галакронда.",
  },
  {
    id: "grizzly-ironhide-ursa",
    entryId: 900046,
    name: "Урса Железная Шкура Урсок",
    zone: "Седые холмы",
    continent: "Нордскол",
    level: "73-76",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Яростный рев (рассекает броню), размашистые удары по троим",
    bulkLoot: "Арктический мех x200",
    bulkItemId: 44128,
    bulkItemCount: 200,
    rareLoot: "Шкура Великого Медведя (уникальная накидка друида)",
    rareItemId: 950046,
    rareDropChance: "2%",
    spawnCoords: "X: 4120, Y: -3120, Z: 285",
    enabled: true,
    notes: "Кожевничество. Святилище в соснах близ Седой Пади.",
  },
  {
    id: "stormpeaks-iron-dwarf-king",
    entryId: 900047,
    name: "Тана Древних Титанов Локендор",
    zone: "Грозовая Гряда",
    continent: "Нордскол",
    level: "78-80",
    difficulty: "elite",
    respawnHours: 5,
    mechanic: "Электрический разряд молнии, щит из чистой энергии титанов",
    bulkLoot: "Титановый слиток x500",
    bulkItemId: 37663,
    bulkItemCount: 500,
    rareLoot: "Скрижаль Титанов (реликвия: увеличивает силу прокачки артефакта)",
    rareItemId: 950047,
    rareDropChance: "1%",
    spawnCoords: "X: 6720, Y: -1120, Z: 890",
    enabled: true,
    notes: "Горное дело. Руины кузниц титанов.",
  },
  {
    id: "zuldrak-drakkari-prophet",
    entryId: 900048,
    name: "Пророк Драккари Кровопийца",
    zone: "Зул'Драк",
    continent: "Нордскол",
    level: "75-78",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Кровавый жертвенный алтарь, поглощение душ павших богов",
    bulkLoot: "Ледошип x1000",
    bulkItemId: 36907,
    bulkItemCount: 1000,
    rareLoot: "Маска Пророка Драккари (трансмог шлем с эффектом глаз тролля)",
    rareItemId: 950048,
    rareDropChance: "2%",
    spawnCoords: "X: 5240, Y: -1850, Z: 260",
    enabled: true,
    notes: "Травничество. Ступени алтаря Гундрака.",
  },
  {
    id: "crystalsong-magic-golem",
    entryId: 900049,
    name: "Кристальный Хранитель Песни",
    zone: "Лес Хрустальной Песни",
    continent: "Нордскол",
    level: "77-80",
    difficulty: "mini-boss",
    respawnHours: 3,
    mechanic: "Кристаллический взрыв, отражение урона обратно в атакующих",
    bulkLoot: "Извечная жизнь x500",
    bulkItemId: 35625,
    bulkItemCount: 500,
    rareLoot: "Хрустальный цветок (игрушка: окружает игрока кристаллами)",
    rareItemId: 950049,
    rareDropChance: "2.5%",
    spawnCoords: "X: 5410, Y: 120, Z: 165",
    enabled: true,
    notes: "Наложение чар. Прямо под висячим Далараном.",
  },
  {
    id: "wintergrasp-siege-titan",
    entryId: 900050,
    name: "Осадный Механо-Титан Озера",
    zone: "Озеро Ледяных Оков",
    continent: "Нордскол",
    level: "80-83",
    difficulty: "elite",
    respawnHours: 6,
    mechanic: "Осадные ракеты по площади, защитный плазменный купол",
    bulkLoot: "Осколки душ и саронит x1000",
    bulkItemId: 36909,
    bulkItemCount: 1000,
    rareLoot: "Осадный Двигатель Титанов (маунт-механотанк)",
    rareItemId: 950050,
    rareDropChance: "0.8%",
    spawnCoords: "X: 4520, Y: 2840, Z: 395",
    enabled: true,
    notes: "Горное дело и инженерия. В центре крепости Озера.",
  },

  // ================= Pandaria (43-50) =================
  {
    id: "jade-serpent-spirit",
    entryId: 900019,
    name: "Дух Нефритового Змея Юй'лун",
    zone: "Нефритовый лес",
    continent: "Пандария",
    level: "85-88",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Исцеляющий туман соратникам, нефритовое пламя по земле",
    bulkLoot: "Ветрошёлк x1000",
    bulkItemId: 79251,
    bulkItemCount: 1000,
    rareLoot: "Осколок Чистого Нефрита (компонент легендарного квеста)",
    rareItemId: 950019,
    rareDropChance: "1%",
    spawnCoords: "X: 920, Y: -2410, Z: 18",
    enabled: true,
    notes: "Портняжество. Храм Нефритового Змея.",
  },
  {
    id: "yaungol-warbringer",
    entryId: 900020,
    name: "Яунгольский Вестник Войны Бату",
    zone: "Вершина Кунь-Лай",
    continent: "Пандария",
    level: "88-90",
    difficulty: "elite",
    respawnHours: 5,
    mechanic: "Боевой рог ярости (+50% скорости атаки), сокрушающий удар копьем",
    bulkLoot: "Руда призрачного железа x1000",
    bulkItemId: 72092,
    bulkItemCount: 1000,
    rareLoot: "Штандарт Вестника Войны (украшение для гильд-зала)",
    rareItemId: 950020,
    rareDropChance: "2%",
    spawnCoords: "X: 3820, Y: 1450, Z: 512",
    enabled: true,
    notes: "Горное дело. Тропа Войны у перевала.",
  },
  {
    id: "sha-of-greed-shadow",
    entryId: 900011,
    name: "Тень Ша Алчности",
    zone: "Дол Четырёх Ветров",
    continent: "Пандария",
    level: "88-90",
    difficulty: "elite",
    respawnHours: 6,
    mechanic: "Аура алчности (урон растет от золота у игрока), теневые щупальца",
    bulkLoot: "Призрачное железо x1000",
    bulkItemId: 72092,
    bulkItemCount: 1000,
    rareLoot: "Кристалл Ша (редчайший реагент трансмутации)",
    rareItemId: 950011,
    rareDropChance: "1%",
    spawnCoords: "X: -540, Y: 120, Z: 45",
    enabled: true,
    notes: "Горное дело. Поля полугорья.",
  },
  {
    id: "krasarang-kraken",
    entryId: 900051,
    name: "Кракен Глубин Красаранга",
    zone: "Красарангские джунгли",
    continent: "Пандария",
    level: "86-89",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Стягивание щупальцами в воду, чернильное облако (100% промахов)",
    bulkLoot: "Пандаренская чешуя x1000",
    bulkItemId: 72120,
    bulkItemCount: 1000,
    rareLoot: "Жемчужина Красаранга (маунт Водный Долгоног)",
    rareItemId: 950051,
    rareDropChance: "1%",
    spawnCoords: "X: -2120, Y: -850, Z: 2",
    enabled: true,
    notes: "Кожевничество. Бухта у Дозора Чжу.",
  },
  {
    id: "dread-wastes-klaxxi-paragon",
    entryId: 900052,
    name: "Павший Идеал Клакси Вороний Взор",
    zone: "Жуткие пустоши",
    continent: "Пандария",
    level: "89-91",
    difficulty: "elite",
    respawnHours: 5,
    mechanic: "Звуковой импульс, янтарная тюрьма на второго танка",
    bulkLoot: "Кипарит x1000",
    bulkItemId: 72093,
    bulkItemCount: 1000,
    rareLoot: "Янтарный клинок Идеала (трансмог одноручный янтарный меч)",
    rareItemId: 950052,
    rareDropChance: "1.5%",
    spawnCoords: "X: -1450, Y: 3820, Z: 62",
    enabled: true,
    notes: "Горное дело. У Янтарного Свода.",
  },
  {
    id: "townlong-mantid-empress-shadow",
    entryId: 900053,
    name: "Тень Богомола Пожиратель Роя",
    zone: "Танлунские степи",
    continent: "Пандария",
    level: "88-91",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Роение саранчи по рейду, взрывной кокон при 50% HP",
    bulkLoot: "Шёлковая трава x1000",
    bulkItemId: 72235,
    bulkItemCount: 1000,
    rareLoot: "Кокон Богомола (боевой питомец юный богомол)",
    rareItemId: 950053,
    rareDropChance: "2%",
    spawnCoords: "X: 1850, Y: 4120, Z: 85",
    enabled: true,
    notes: "Травничество. Лагерь у Стены Драконьего Хребта.",
  },
  {
    id: "vale-golden-lotus-protector",
    entryId: 900054,
    name: "Древний Страж Золотого Лотоса",
    zone: "Вечноцветущий дол",
    continent: "Пандария",
    level: "90-92",
    difficulty: "elite",
    respawnHours: 6,
    mechanic: "Золотой вихрь лепестков, аура очищения от скверны",
    bulkLoot: "Золотой лотос x500",
    bulkItemId: 72238,
    bulkItemCount: 500,
    rareLoot: "Цветок Вечности (реликвия: ускоряет восстановление способностей на 5%)",
    rareItemId: 950054,
    rareDropChance: "0.8%",
    spawnCoords: "X: 1450, Y: 850, Z: 285",
    enabled: true,
    notes: "Травничество. Центр Дола у Дворца Могу'шан.",
  },
  {
    id: "timeless-isle-cinderfall",
    entryId: 900055,
    name: "Пеплопад Разрушитель Времени",
    zone: "Вневременный остров",
    continent: "Пандария",
    level: "92-94",
    difficulty: "elite",
    respawnHours: 6,
    mechanic: "Огненный метеоритный дождь, временная петля (откат HP на 10 сек назад)",
    bulkLoot: "Вневременные монеты x2000",
    bulkItemId: 105952,
    bulkItemCount: 2000,
    rareLoot: "Поводья Небесного Золотого Облачного Змея (эпический маунт)",
    rareItemId: 950055,
    rareDropChance: "0.5%",
    spawnCoords: "X: -6120, Y: -4850, Z: 12",
    enabled: true,
    notes: "Особая зона. Руины Огненного Святилища.",
  },

  // ================= Draenor (51-55) =================
  {
    id: "ogre-warchief",
    entryId: 900021,
    name: "Огрский Военачальник Друз'гар",
    zone: "Хребет Ледяного Огня",
    continent: "Дренор",
    level: "92-95",
    difficulty: "elite",
    respawnHours: 5,
    mechanic: "Прыжок с раскалыванием земли, каменный щит при 20% HP",
    bulkLoot: "Истинное железо x1000",
    bulkItemId: 109119,
    bulkItemCount: 1000,
    rareLoot: "Трофей Военачальника (уникальный питомец-огренок)",
    rareItemId: 950021,
    rareDropChance: "1.5%",
    spawnCoords: "X: 6120, Y: 4850, Z: 120",
    enabled: true,
    notes: "Горное дело. Крепость Тяжкого Молота.",
  },
  {
    id: "rock-giant-elder",
    entryId: 900022,
    name: "Каменный Старейшина-Великан",
    zone: "Горгронд",
    continent: "Дренор",
    level: "94-96",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Каменный град по дальникам, землетрясение с замедлением на 60%",
    bulkLoot: "Чернорудная руда x1000",
    bulkItemId: 109118,
    bulkItemCount: 1000,
    rareLoot: "Ядро Горгронда (реагент для улучшения экипировки 985→1000)",
    rareItemId: 950022,
    rareDropChance: "2%",
    spawnCoords: "X: 5420, Y: 1240, Z: 95",
    enabled: true,
    notes: "Горное дело. Долина первобытных камней Гормока.",
  },
  {
    id: "talador-arakkoa-sunpriest",
    entryId: 900056,
    name: "Солнечный Жрец Араккоа Икарос",
    zone: "Таладор",
    continent: "Дренор",
    level: "95-97",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Луч солнечной ярости, призыв солнечных вспышек по рейду",
    bulkLoot: "Роскошный мех x1000",
    bulkItemId: 111557,
    bulkItemCount: 1000,
    rareLoot: "Солнечные перья Араккоа (трансмог плащ с солнечным светом)",
    rareItemId: 950056,
    rareDropChance: "2%",
    spawnCoords: "X: 3120, Y: 2450, Z: 145",
    enabled: true,
    notes: "Портняжество. Разрушенный Аукиндон в Таладоре.",
  },
  {
    id: "shadowmoon-void-horror",
    entryId: 900057,
    name: "Ужас Бездны Темной Звезды",
    zone: "Долина Призрачной Луны (Дренор)",
    continent: "Дренор",
    level: "98-100",
    difficulty: "elite",
    respawnHours: 5,
    mechanic: "Воронка пустоты (стяжка игроков), черные дыры под ногами",
    bulkLoot: "Сырая кожа зверя x1000",
    bulkItemId: 110609,
    bulkItemCount: 1000,
    rareLoot: "Осколок Темной Звезды (маунт Пустотный Опустошитель)",
    rareItemId: 950057,
    rareDropChance: "0.9%",
    spawnCoords: "X: 850, Y: -1450, Z: 48",
    enabled: true,
    notes: "Кожевничество. Карьер Темной Звезды близ Карабора.",
  },
  {
    id: "tanaan-fel-annihilator",
    entryId: 900058,
    name: "Аннигилятор Скверны Ксул'горат",
    zone: "Танаанские джунгли",
    continent: "Дренор",
    level: "100-103",
    difficulty: "elite",
    respawnHours: 6,
    mechanic: "Лазерный залп Скверны, призыв оскверненных инферналов",
    bulkLoot: "Оскверненная кровь x500",
    bulkItemId: 127759,
    bulkItemCount: 500,
    rareLoot: "Оскверненный силовой двигатель (маунт Оскверненный Разрушитель)",
    rareItemId: 950058,
    rareDropChance: "0.7%",
    spawnCoords: "X: 4120, Y: -120, Z: 85",
    enabled: true,
    notes: "Инженерия и кузнечное дело. Цитадель Адского Пламени снаружи.",
  },

  // ================= Broken Isles & Argus (56-60) =================
  {
    id: "felbat-broodmother",
    entryId: 900023,
    name: "Праматерь Осквернённых Нетопырей",
    zone: "Азсуна",
    continent: "Расколотые острова",
    level: "108-110",
    difficulty: "elite",
    respawnHours: 5,
    mechanic: "Звуковой вопль немоты, пикирование стаей, лужи скверны",
    bulkLoot: "Лейстонит x1000",
    bulkItemId: 123918,
    bulkItemCount: 1000,
    rareLoot: "Крыло Нетопыря (уникальный трансмог-плащ со свечением)",
    rareItemId: 950023,
    rareDropChance: "1%",
    spawnCoords: "X: -450, Y: 6850, Z: 95",
    enabled: true,
    notes: "Горное дело. Друидская роща Азсуны.",
  },
  {
    id: "ancient-tauren-spirit",
    entryId: 900024,
    name: "Дух Древнего Тотема Крутогорья",
    zone: "Крутогорье",
    continent: "Расколотые острова",
    level: "109-111",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Призыв предков-орлов, защитный каменный тотем на 500к щита",
    bulkLoot: "Зверобой и лисоцвет x1000",
    bulkItemId: 124101,
    bulkItemCount: 1000,
    rareLoot: "Тотем Крутогорья (реликвия шамана: открывает усиленный тотем)",
    rareItemId: 950024,
    rareDropChance: "1.5%",
    spawnCoords: "X: 4850, Y: 3850, Z: 740",
    enabled: true,
    notes: "Травничество. Пик Ветрокрылых у вершины горы.",
  },
  {
    id: "suramar-nightborne-inquisitor",
    entryId: 900059,
    name: "Инквизитор Порочных Ночнорожденных",
    zone: "Сурамар",
    continent: "Расколотые острова",
    level: "110-112",
    difficulty: "elite",
    respawnHours: 6,
    mechanic: "Искажение маны Ночного Колодца, клетка чародейской тюрьмы",
    bulkLoot: "Древняя мана x2000",
    bulkItemId: 141446,
    bulkItemCount: 2000,
    rareLoot: "Кристалл Ночного Колодца (маунт Манапард Сурамара)",
    rareItemId: 950059,
    rareDropChance: "0.8%",
    spawnCoords: "X: 1850, Y: 4120, Z: 110",
    enabled: true,
    notes: "Ювелирное дело. Терраса Ночного Колодца снаружи города.",
  },
  {
    id: "stormheim-valkyr-dreadmaiden",
    entryId: 900060,
    name: "Дева Смерти Валькира Хелии",
    zone: "Штормхейм",
    continent: "Расколотые острова",
    level: "109-111",
    difficulty: "rare-elite",
    respawnHours: 4,
    mechanic: "Призыв тумана Хельхейма, цепи мертвых душ с оглушением",
    bulkLoot: "Штормовая чешуя x1000",
    bulkItemId: 124113,
    bulkItemCount: 1000,
    rareLoot: "Крылья Валькиры (трансмог на спину со светящимися крыльями)",
    rareItemId: 950060,
    rareDropChance: "1.2%",
    spawnCoords: "X: 3820, Y: 1450, Z: 245",
    enabled: true,
    notes: "Кожевничество. Врата Хельхейма на побережье Штормхейма.",
  },
  {
    id: "awakened-void-sentinel",
    entryId: 900025,
    name: "Пробуждённый Страж Пустоты",
    zone: "Расколотый берег",
    continent: "Расколотые острова",
    level: "112-114",
    difficulty: "elite",
    respawnHours: 8,
    mechanic: "Разлом Пустоты (телепортация случайных игроков), иммунитет к магии 8 сек",
    bulkLoot: "Тени пустоты и демоническая сталь x1000",
    bulkItemId: 123919,
    bulkItemCount: 1000,
    rareLoot: "Сущность Пробуждения x25 (джекпот) + маунт Морок Пустоты",
    rareItemId: 950025,
    rareDropChance: "0.5%",
    spawnCoords: "X: -1850, Y: 2150, Z: 18",
    enabled: true,
    notes: "ГЛАВНЫЙ БОСС: основной открытый источник фарма Сущностей Пробуждения.",
  },
];
